import os
import operator
from typing import TypedDict, List, Annotated, Any
from langgraph.graph import StateGraph, START, END
from langgraph.constants import Send
from langchain_anthropic import ChatAnthropic
from langchain_core.messages import SystemMessage, HumanMessage
import markdown

# 1. DEFINE OVERALL PIPELINE STATE
class PipelineState(TypedDict):
    product: dict
    templates: List[dict]
    # operator.add allows workers to append their generated markdown docs concurrently
    generated_assets: Annotated[List[dict], operator.add]
    final_output_path: str

# 2. DEFINE WORKER STATE
class WorkerState(TypedDict):
    product: dict
    template: dict

# 3. DEFINE THE NODES
def dispatch_templates(state: PipelineState) -> List[Send]:
    """
    Scatter Node: Takes the inbound request and fans it out.
    Spawns an independent parallel worker for each individual template.
    """
    templates = state.get("templates", [])
    product = state.get("product", {})
    return [Send("generate_asset_worker", {"product": product, "template": t}) for t in templates]

def generate_asset_worker(state: WorkerState):
    """
    Worker Node: Dedicated AI copywriter for a single template. (Parallel Execution)
    Replaces the await Promise.all() block in the old TypeScript server.
    """
    product = state["product"]
    template = state["template"]
    
    # Text replacement similar to server.ts
    full_prompt = template.get("template", "") \
        .replace('{{PRODUCT_TITLE}}', product.get("title", "")) \
        .replace('{{PRODUCT_TYPE}}', product.get("type", "")) \
        .replace('{{SHORT_DESCRIPTION}}', product.get("shortDescription", "")) \
        .replace('{{DETAILED_DESCRIPTION}}', product.get("detailedDescription", ""))
        
    try:
        # Visual Node initialization 
        llm = ChatAnthropic(model="claude-3-haiku-20240307", max_tokens=4000)
        messages = [
            SystemMessage(content="You are an elite automated copywriter for Tina Marie. Apply the 9 Business Fundamentals framework and Persuasive Writing protocols. Be highly specific, formatting output tightly in markdown. DO NOT output conversational filler; ONLY output the asset requested."),
            HumanMessage(content=full_prompt)
        ]
        
        print(f"[AUTO-BUILDER] Visual Worker started: {template.get('id')}")
        response = llm.invoke(messages)
        content = response.content
        if isinstance(content, list):
            content = content[0].get("text", str(content))
            
        # Add visual stamp so user sees this was AI generated
        content += f"\n\n*Generated by AI Worker ({template.get('id')}) for {product.get('title')}*"
        
        base_dir = os.path.join(os.getcwd(), "generated", str(product.get("id", "demo")))
        os.makedirs(base_dir, exist_ok=True)
        file_path = os.path.join(base_dir, f"{template.get('id')}.md")
        
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)
            
        print(f"[AUTO-BUILDER] Saved visual node output: {file_path}")
        
    except Exception as e:
        print(f"Error generating {template.get('id')}: {e}")
        content = f"Error: {e}"
        
    # Return the generated text string up to the aggregator
    return {"generated_assets": [{"id": template.get("id"), "content": content}]}

def assemble_html_block(state: PipelineState):
    """
    Aggregator Node: Runs AFTER all generate_asset_worker nodes finish.
    Gathers generated content and injects into GHL HTML template.
    """
    assets = state.get("generated_assets", [])
    product = state.get("product", {})
    
    sales_page_asset = next((a for a in assets if a["id"] == "sales_page"), None)
    
    if sales_page_asset:
        print("[AUTO-BUILDER] Assembling Final HTML Deployment String...")
        html_content = markdown.markdown(sales_page_asset["content"])
        
        final_html = f"<html><body><div class='ai-generated-content'>{html_content}</div></body></html>"
        
        base_dir = os.path.join(os.getcwd(), "generated", str(product.get("id", "demo")))
        os.makedirs(base_dir, exist_ok=True)
        html_path = os.path.join(base_dir, f"ghl-deploy-{product.get('id')}.html")
        
        with open(html_path, "w", encoding="utf-8") as f:
            f.write(final_html)
            
        print(f"[AUTO-BUILDER] Built GHL Integration file: {html_path}")
        return {"final_output_path": html_path}
        
    return {"final_output_path": "No sales page asset generated."}

# 4. ORCHESTRATE THE VISUAL GRAPH
workflow = StateGraph(PipelineState)

# We map individual nodes that will show up visually in LangGraph Studio
workflow.add_node("generate_asset_worker", generate_asset_worker)
workflow.add_node("assemble_html_block", assemble_html_block)

# 5. CREATE EDGES
# Send the Start edge directly to the scatter node logic to trigger parallel workers
workflow.add_conditional_edges(START, dispatch_templates, ["generate_asset_worker"])

# Once workers finish, pass their collective outputs into the HTML Assembler
workflow.add_edge("generate_asset_worker", "assemble_html_block")

# Finish the sequence
workflow.add_edge("assemble_html_block", END)

# Compile into a runnable state machine network for Flowise/LangGraph UI
graph = workflow.compile()
